name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build all crates
      run: cargo build --verbose

  casino_cards_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Run tests for casino_cards
      run: cargo test --verbose --manifest-path crates/casino_cards/Cargo.toml

  poker_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Run tests for poker
      run: cargo test --verbose --manifest-path crates/poker/Cargo.toml
